#!/usr/bin/env bash
# =============================================================================
# setup_keys.sh — Interactively configure Kraken API keys for live trading
# =============================================================================
#
# Run this ONCE before going live.  It will:
#   1. Guide you through creating a Kraken API key with the right permissions
#   2. Prompt for your API key and secret
#   3. Write them to a local .env file (gitignored — never committed)
#   4. Test the credentials against Kraken's Balance endpoint
#
# Usage:
#   chmod +x setup_keys.sh
#   ./setup_keys.sh
#
# After this script succeeds:
#   ./go_live.sh       — start the bot in full live mode
#   ./run_sandbox.sh   — continue paper trading (no keys needed)
# =============================================================================

set -e
cd "$(dirname "$0")"

# ---------------------------------------------------------------------------
# Step 1 — instructions: how to create the Kraken API key
# ---------------------------------------------------------------------------
cat <<'INSTRUCTIONS'

============================================================
  KrakBot — Live API Key Setup
============================================================

Before you enter your keys, make sure you have created a
Kraken API key with the following permissions:

  ✅  Query Funds          (read balances)
  ✅  Query Open Orders    (read order status)
  ✅  Query Closed Orders  (read trade history)
  ✅  Create & Modify Orders  (place orders)
  ✅  Cancel/Close Orders     (cancel orders)

  ❌  Withdraw Funds       — DO NOT enable
  ❌  Access WebSockets    — not required

How to create the key:
  1. Log in to kraken.com → Security → API → Add Key
  2. Give it a name, e.g. "KrakBot live"
  3. Tick ONLY the five checkboxes above
  4. Click Generate Key
  5. Copy both the API Key and the Private Key (shown only once!)

Optionally set an IP whitelist to your server/Replit IP for extra safety.

============================================================
INSTRUCTIONS

read -rp "  Press Enter when you have your key and secret ready... "
echo ""

# ---------------------------------------------------------------------------
# Step 2 — prompt for API key and secret
# ---------------------------------------------------------------------------
echo "Enter your Kraken API Key (visible in Kraken dashboard):"
read -r api_key
echo ""

echo "Enter your Kraken API Secret (Private Key — shown only when created):"
read -rs api_secret   # -s = silent (don't echo)
echo ""
echo ""

if [[ -z "$api_key" || -z "$api_secret" ]]; then
    echo "❌  API key or secret is empty. Aborting." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Step 3 — write to .env (gitignored)
# ---------------------------------------------------------------------------
ENV_FILE=".env"

# Preserve any existing non-credential lines if .env already exists
if [[ -f "$ENV_FILE" ]]; then
    # Remove old key/secret lines
    grep -vE '^(KRAKEN_API_KEY=|KRAKEN_API_SECRET=)' "$ENV_FILE" > "${ENV_FILE}.tmp" 2>/dev/null || true
    mv "${ENV_FILE}.tmp" "$ENV_FILE"
else
    # Seed with live-mode defaults
    cat > "$ENV_FILE" <<'DEFAULTS'
# KrakBot live configuration — generated by setup_keys.sh
USE_BULL_BEAR_TRADER=true
USE_PAPER_BROKER=false
KRAKEN_SANDBOX=false
BOT_MODE=live
BTC_BULL_RUN_FLOOR=65000
BREAKOUT_CONFIDENCE_MIN=0.55
DEFAULTS
fi

# Append the credentials
{
    echo "KRAKEN_API_KEY=${api_key}"
    echo "KRAKEN_API_SECRET=${api_secret}"
} >> "$ENV_FILE"

echo "✅  Credentials written to ${ENV_FILE}"
echo "    (This file is gitignored — it will never be committed.)"
echo ""

# ---------------------------------------------------------------------------
# Step 4 — test credentials against Kraken Balance endpoint
# ---------------------------------------------------------------------------
echo "Testing credentials against Kraken /0/private/Balance…"
echo ""

python3 - <<PYEOF
import os, sys

# Load just the credentials from .env
creds = {}
try:
    with open(".env") as f:
        for line in f:
            line = line.strip()
            if line.startswith("KRAKEN_API_KEY="):
                creds["KRAKEN_API_KEY"] = line.split("=", 1)[1]
            elif line.startswith("KRAKEN_API_SECRET="):
                creds["KRAKEN_API_SECRET"] = line.split("=", 1)[1]
except FileNotFoundError:
    print("ERROR: .env file not found.")
    sys.exit(1)

os.environ.update(creds)

# Import broker and test
sys.path.insert(0, "project")
from broker.broker import LiveBroker

broker = LiveBroker(dry_run=True)
ok = broker.validate_credentials()

if ok:
    print("")
    print("============================================================")
    print("  ✅  Credentials verified!  KrakBot is ready to go live.")
    print("  Run:  ./go_live.sh")
    print("============================================================")
    sys.exit(0)
else:
    print("")
    print("============================================================")
    print("  ❌  Credential check failed.")
    print("  Double-check the key and secret on kraken.com → Security → API.")
    print("  Then run ./setup_keys.sh again.")
    print("============================================================")
    sys.exit(1)
PYEOF
